spring:
  main:
    banner-mode: off
  security:
    user:
      name: admin
      password: 123456
      roles: ADMIN
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver # 暂时不用理会
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

